extends:
  import: classic
  file: pipeline.yaml
agent:
  image: gcr.io/jenkinsxio/builder-jx
pipelines:
  overrides:
    - stage: build
      volumes:
        - name: kaniko-docker-config
          secret:
            secretName: kaniko-docker-cfg
        - name: kaniko-secret
          secret:
            secretName: kaniko-secret
            items:
              - key: kaniko-secret
                path: kaniko/kaniko-secret.json
      containerOptions:
        volumeMounts:
          - mountPath: /kaniko/.docker
            name: kaniko-docker-config
          - mountPath: /secrets
            name: kaniko-secret
        resources:
          limits:
            memory: 16Gi
            cpu: 3
          requests:
            memory: 12Gi
            cpu: 2
        env:
          - name: DOCKER_REGISTRY
            valueFrom:
              configMapKeyRef:
                name: jenkins-x-docker-registry
                key: docker.registry
          - name: DOCKER_REGISTRY_ORG
            valueFrom:
              configMapKeyRef:
                name: jenkins-x-docker-registry
                key: docker.org 
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /secrets/kaniko/kaniko-secret.json
  pullRequest:
    build:
      steps:
      - sh: /kaniko/executor --cache=true --cache-dir=/workspace --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION --cache-repo=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/cache
        name: container-build
        image: gcr.io/kaniko-project/executor
  release:
    build:
      steps:
        - sh: /kaniko/executor --cache=true --cache-dir=/workspace --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION --cache-repo=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/cache
          name: container-build
          image: gcr.io/kaniko-project/executor
    promote:
      steps:
        - sh: jx step changelog --version v\$(cat VERSION)
          name: changelog
          image: gcr.io/jenkinsxio/jx
