extends:
  import: classic
  file: git/pipeline.yaml
pipelines:
  release:
    setVersion:
      replace: true
      steps:
        - name: unshallow
          sh: 'git fetch --unshallow'
        - name: fetch-tags
          sh: 'git fetch'
        - name: create-version-file
          sh: 'jx step next-version --version=$(make version~print)'
