extends:
  import: classic
  file: pipeline.yaml
agent:
  label: jenkins-go
  container: jenkinsxio/jenkins-x-installer:0.0.27
pipelines:
  release:
    pipeline:
      agent:
        image: gcr.io/build-jx-prod/jxlabs-nos-master/jxl
      options:
        volumes:
        - name: jx-boot-secrets
          secret:
            defaultMode: 420
            secretName: jx-boot-secrets
        containerOptions:
          env:
          - name: XDG_CONFIG_HOME
            value: "/builder/home"
          - name: JX_SECRETS_YAML
            value: "/secrets/jx-boot/secrets.yaml"
          volumeMounts:
          - mountPath: /secrets/jx-boot
            name: jx-boot-secrets
      stages:
      - name: release
        steps:
        - args:
          - step
          - git
          - validate
          command: jx
          dir: /workspace/source
          name: validate-git
        - args:
          - step
          - verify
          - preinstall
          - --disable-verify-packages
          - --provider-values-dir="kubeProviders"
          command: jx
          dir: /workspace/source
          name: verify-preinstall
        - args:
          - step
          - create
          - helmfile
          - --values
          - ../jx-requirements.values.yaml.gotmpl
          command: jx
          dir: /workspace/source
          name: generate-helmfile
        - command: helmfile diff || true
          dir: /workspace/source/system
          name: helmfile-system-diff
        - args:
          - sync
          command: helmfile
          dir: /workspace/source/system
          name: helmfile-system
        - args:
          - step
          - verify
          - ingress
          - --ingress-namespace=nginx
          - --ingress-service=nginx-ingress-controller
          command: jx
          dir: /workspace/source
          name: verify-ingress
        - command: helmfile diff || true
          dir: /workspace/source/apps
          name: helmfile-apps-diff
        - args:
          - sync
          command: helmfile
          dir: /workspace/source/apps
          name: helmfile-apps
        - args:
          - step
          - git
          - credentials
          - -o
          - /builder/home/git/credentials
          command: jx
          dir: /workspace/source
          name: git-creds
        - args:
          - step
          - verify
          - env
          command: jx
          dir: /workspace/source
          name: verify-jenkins-x-environment
        - args:
          - step
          - scheduler
          - config
          - apply
          - --direct=true
          command: jx
          dir: /workspace/source
          name: install-pipelines
        - args:
          - update
          - webhooks
          - --verbose
          - --warn-on-fail
          command: jx
          dir: /workspace/source
          name: update-webhooks
        - args:
          - step
          - verify
          - install
          - --pod-wait-time
          - 30m
          command: jx
          dir: /workspace/source
          name: verify-installation

  pullRequest:
    pipeline:
      agent:
        image: gcr.io/build-jx-prod/jxlabs-nos-master/jxl
      options:
        volumes:
        - name: jx-boot-secrets
          secret:
            defaultMode: 420
            secretName: jx-boot-secrets
        containerOptions:
          env:
          - name: XDG_CONFIG_HOME
            value: "/builder/home"
          - name: JX_SECRETS_YAML
            value: "/secrets/jx-boot/secrets.yaml"
          volumeMounts:
          - mountPath: /secrets/jx-boot
            name: jx-boot-secrets
      stages:
      - name: pr-checks
        steps:
        - args:
          - step
          - create
          - helmfile
          - --values
          - ../jx-requirements.values.yaml.gotmpl
          command: jx
          dir: /workspace/source
          name: generate-helmfile
        - args:
          - lint
          command: helmfile
          dir: /workspace/source/system
          name: lint-helmfile-system
        - args:
          - lint
          command: helmfile
          dir: /workspace/source/apps
          name: lint-helmfile-apps



