agent:
  label: jenkins-go
  container: go
pipelines:
  pullRequest:
    setVersion:
      replace: true
      steps:
        - name: unshallow
          sh: 'git fetch --unshallow --recurse-submodules=false'
        - name: fetch-tags-also
          sh: 'git fetch --recurse-submodules=false'
        - name: create-version-file
          sh: 'jx step next-version --version=$(make version~print)'
    build:
      steps:
      - sh: jxl jenkins trigger --multi-branch-project --branch=$BRANCH_NAME --tail
        name: trigger
        image: gcr.io/build-jx-prod/jxlabs-nos-master/jxl
  release:
    setVersion:
      replace: true
      steps:
        - name: unshallow
          sh: 'git fetch --unshallow --recurse-submodules=false'
        - name: fetch-tags-also
          sh: 'git fetch --recurse-submodules=false'
        - name: create-version-file
          sh: 'jx step next-version --version=$(make version~print)'
        - name: tag-version
          sh: 'jx step tag'
        - name: update-changelog
          sh: 'jx step changelog'
    build:
      steps:
      - sh: jxl jenkins trigger --multi-branch-project --branch=$BRANCH_NAME --tail
        name: trigger
        image: gcr.io/build-jx-prod/jxlabs-nos-master/jxl
