agent:
  label: jenkins-go
  container: go
pipelines:
  pullRequest:
    build:
      steps:
      - sh: jxl jenkins trigger
        name: trigger
        image: gcr.io/build-jx-prod/jxlabs-nos-master/jxl
  release:
    build:
      steps:
      - sh: jxl jenkins trigger
        name: trigger
        image: gcr.io/build-jx-prod/jxlabs-nos-master/jxl
